[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
matplotlib = "^3.10.0"
ipykernel = "^6.29.5"
